### ISSUE TITLE
Enhancement !bangs

### ISSUE THREAD

**Issue by TriMoon** [duckduckgo/firefox-zeroclickinfo#40]
People should be able to choose which bangs to show in the popup as quick access.
The current featured listing is just taking space for those NOT wanting them...

**Comment by edgesince84** [comment]
Thanks for the suggestion, TriMoon.  We'll take this under consideration.

**Comment by TriMoon** [comment]
Why would anyone who uses a "**non-tracking**" search engine, to have a functionality that would **track** your most used bangs? o.O
So in short no.

**Comment by edgesince84** [comment]
Hi TriMoon, where did you see someone recommend tracking your most-used bangs?

**Comment by tagawa** [comment]
@TriMoon I've suggested this internally so I'll close this task. Thanks for the suggestion.
