### ISSUE TITLE
ReferenceError: window is not defined leads to segfault under firefox 47.0

### ISSUE THREAD

**Issue by jkearisman** [duckduckgo/firefox-zeroclickinfo#41]
OS: arch linux
Firefox Version: 47.0
Addon Version: 0.5.2
Other Addons: Vimperator, noscript

console.error: duckduckgo_plus: 
  Message: ReferenceError: window is not defined
  Stack:
    exports.create/menuItem<.onMessage@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-zadieub7xozojw-at-jetpack/lib/ddg-askdax.js:41:1
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9`
`emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
workerMessageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:455:17
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37

Assertion failure: !mDoingStableStates, at /build/firefox/src/firefox-47.0/xpcom/base/CycleCollectedJSRuntime.cpp:1305
#01: ???[/usr/lib/firefox/libxul.so +0xe66de4]
#02: ???[/usr/lib/firefox/libxul.so +0xa32ac6]
#03: NS_InvokeByIndex[/usr/lib/firefox/libxul.so +0xa3adda]
#04: ???[/usr/lib/firefox/libxul.so +0xe74443]
#05: ???[/usr/lib/firefox/libxul.so +0xe7b6f4]
#06: ???[/usr/lib/firefox/libxul.so +0x29a9be9]
#07: ???[/usr/lib/firefox/libxul.so +0x29a3e8b]
#08: ???[/usr/lib/firefox/libxul.so +0x29a9825]
#09: ???[/usr/lib/firefox/libxul.so +0x29a9b17]
#10: ???[/usr/lib/firefox/libxul.so +0x29aa15c]
#11: ???[/usr/lib/firefox/libxul.so +0x2bc4be0]
#12: ??? (???:???)
zsh: segmentation fault (core dumped)  firefox

**Comment by edgesince84** [comment]
Hi @jkearisman, thanks for opening this issue!  We'll review it ASAP.

**Comment by moollaza** [comment]
@jkearisman can you please give us steps to reproduce this error?

/cc @mrshu is this useful? Anything else you need?

**Comment by jkearisman** [comment]
Sorry, I've been trying to figure out a way to consistently reproduce it, but it seems to just happen randomly every few hours. Might be a problem with my system. If I figure anything out, I'll let you know.

**Comment by mrshu** [comment]
@jkearisman Please do let us know if you could reproduce this issue. It seems to be e10s (firefox running in multiple processes) related and thus it will not be easy to reproduce.

In the meantime I will try to get a sense of what could have caused the issue in the first place and make sure it is multiprocess-ready.

Thanks again for the report!

**Comment by mrshu** [comment]
@jkearisman I was able to reproduce this issue and put together a fix in #50. Please do let us know if you run into any other issue.

Thanks!

**Comment by mephinet** [comment]
probably caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1235183 and will be fixed in FF 50.
