### ISSUE TITLE
Links from search results will not open in new tab

### ISSUE THREAD

**Issue by rasnal** [duckduckgo/firefox-zeroclickinfo#59]
i have tried everything i can think of. Setting on firefox are set to open all links in a new tab but duckduckgo search result links are the only thing that will not work.

**Comment by mrshu** [comment]
Thanks for reaching out to us @rasnal.

Can this be traced back to the Firefox browser extension? Do the links on DuckDuckGo open in new tab when you disable it?

Otherwise it seems that this might be frontend related (cc @bbraithwaite).

**Comment by bbraithwaite** [comment]
There is a change on the way for this.

**Comment by bbraithwaite** [comment]
In addition, I assume you have the DDG 'Opens results in new windows/tabs' setting to ON?

**Comment by rasnal** [comment]
@mrshu I have tried with the firefox options disabled and while there are on. either way the links from searches will not open in new tab but the search results do. i have also installed the firefox addon "open link in new tab" to try and force it but still ddg links wont open in new tab. 

@bbraithwaite i do not see an option for 'Opens results in new windows/tabs' in the DDG options. can only find it in firefox options witch works with google but i hate google and would much rather use ddg.
 if im over looking an option menu besides the options in the addon manager please let me know where to find it ;P

**Comment by bbraithwaite** [comment]
@rasnal Via the hamburger menu (top right) of the main DDG site, go to 'Advanced Settings' and on the main settings page there is an option 'Opens results in new windows/tabs'. Does switching that on help?

**Comment by rasnal** [comment]
@bbraithwaite  That option is so the search results open in a new tab/window. my problem is after that when you click on a link from the search page. i want the search result page to remain open after clicking on a link but it wont, all options in my browser are set to do this but DDG isnt listening to them.

**Comment by bbraithwaite** [comment]
@rasnal That option could be worded better, but I think it is in fact what you need. Did you try it?

**Comment by rasnal** [comment]
@bbraithwaite  Ah Ha you are correct sir. I found the options you were talking about and changed it. it is now working perfectly. thank you for the help and you are right that option could be worded a little better.  thanks again for the help ;)

**Comment by bbraithwaite** [comment]
@rasnal you're welcome! Glad to hear that you found it.
