### ISSUE TITLE
Use HTML5's placeholder attribute for search input

### ISSUE THREAD

**Issue by CIAvash** [duckduckgo/firefox-zeroclickinfo#6]
I think it's better to use HTML5 placeholder attribute for showing 'Search DuckDuckGo...' when the search input is empty.

**Comment by TriMoon** [comment]
Very weird this was closed using that commit, it has NOTHING todo with OP's request...

**Comment by mrshu** [comment]
@TriMoon agreed, that was a mistake.

The current master version of the popup [does use](https://github.com/duckduckgo/firefox-zeroclickinfo/blob/master/data/html/popup.html#L326) the HTML5 placeholder attribute, however.
