### ISSUE TITLE
DDG Plus breaks slack

### ISSUE THREAD

**Issue by daef** [duckduckgo/firefox-zeroclickinfo#90]
https://our-company.slack.com/messages style suddenly broke for me. Slack support asked me if I use the duckduckgo extension and if so could try to disable it - lo and behold - that did the trick. Why is 'DuckDuckGo Plus' affecting slack.com?

**Comment by jdorweiler** [comment]
@daef thanks for the report. The new version of the extension is blocking trackers and a request from slack was caught up in that. If you restart Firefox it should be fixed now.

**Comment by daef** [comment]
works like a charm :)
